on:
  push:
    branches:
      - main
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.justink40.sg-host.com
          username: ${{ secrets.ftp_login }}
          password: ${{ secrets.ftp_password }}
          server-dir: justink40.sg-host.com/public_html/wp-content/themes/garageflooringllc/